import type { ToolDef } from "./schema";

import {
  getSelection,
  getPageTree,
  getNode,
  findNodes,
  listPages,
  switchPage,
  getCurrentPage,
  pageBounds,
  selectNodes,
} from "./read";
import { createShape, createComponent, createInstance, createPage, createVector } from "./create";
import {
  setFill,
  setStroke,
  setEffects,
  updateNode,
  setLayout,
  setConstraints,
  setRotation,
  setOpacity,
  setRadius,
  setMinMax,
  setText,
  setFont,
  setFontRange,
  setTextResize,
  setVisible,
  setBlend,
  setLocked,
  setStrokeAlign,
  setTextProperties,
  setLayoutChild,
} from "./modify";
import {
  deleteNode,
  cloneNode,
  renameNode,
  reparentNode,
  groupNodes,
  ungroupNode,
  flattenNodes,
  nodeToComponent,
  nodeBounds,
  nodeMove,
  nodeResize,
  nodeAncestors,
  nodeChildren,
  nodeTree,
  nodeBindings,
  nodeReplaceWith,
  arrangeNodes,
  batchUpdate,
} from "./structure";
import {
  listVariables,
  listCollections,
  getVariable,
  findVariables,
  createVariable,
  setVariable,
  deleteVariable,
  bindVariable,
  getCollection,
  createCollection,
  deleteCollection,
} from "./variables";

export const CORE_TOOLS: ToolDef[] = [
  getSelection,
  getPageTree,
  getNode,
  findNodes,
  listPages,
  switchPage,
  getCurrentPage,
  pageBounds,
  selectNodes,
  createShape,
  createPage,
  createComponent,
  createInstance,
  createVector,
  updateNode,
  setLayout,
  setLayoutChild,
  setRadius,
  setFill,
  setStroke,
  setText,
  setTextProperties,
  setFont,
  setTextResize,
  setVisible,
  setConstraints,
  setRotation,
  setOpacity,
  setMinMax,
  setBlend,
  setLocked,
  setStrokeAlign,
  setEffects,
  deleteNode,
  cloneNode,
  renameNode,
  reparentNode,
  groupNodes,
  ungroupNode,
  flattenNodes,
  nodeToComponent,
  nodeBounds,
  nodeMove,
  nodeResize,
  nodeAncestors,
  nodeChildren,
  nodeTree,
  nodeBindings,
  nodeReplaceWith,
  arrangeNodes,
  batchUpdate,
  listVariables,
  listCollections,
  getVariable,
  findVariables,
  createVariable,
  setVariable,
  deleteVariable,
  bindVariable,
  getCollection,
  createCollection,
  deleteCollection,
  setFontRange,
];

export const TOOL_MAP = new Map(CORE_TOOLS.map((tool) => [tool.name, tool]));
